name: Custom Workflow
on:
  push:
    branches:
      - main
      - working-intermediate-thanusha
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Show Env Variable
        run: echo "My env variable is Thanusha"
        env:
          MY_NAME: Thanusha
